name: Building Pillow

on: [workflow_dispatch]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python 3.14
        run: uv python install 3.14

      - name: Install Pillow build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev \
            liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk libharfbuzz-dev \
            libfribidi-dev libxcb1-dev libjpeg62-turbo-dev

      - name: Clone Pillow repository
        run: git clone --recursive --depth 1 https://github.com/python-pillow/Pillow pillow

      - name: Build Pillow
        run: $(uv python find 3.14) -m pip wheel pillow -v

      - name: List files
        run: ls -la && ls -la pillow