name: Building Pillow

on: [workflow_dispatch, push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python 3.14
        run: uv python install 3.14

      - name: Install Pillow build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
            libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
            libharfbuzz-dev libfribidi-dev libxcb1-dev

      - name: Clone Pillow repository
        run: git clone --recursive --depth 1 https://github.com/python-pillow/Pillow pillow

      - name: Clone GRPC repository
        run: git clone --recursive --depth 1 https://github.com/grpc/grpc grpc

      - name: Build GRPC
        run: |
          sudo apt-get install -y libsystemd-dev
          export GRPC_PYTHON_BUILD_WITH_SYSTEMD=1
          $(uv python find 3.14) -m pip wheel grpc -v

      - name: Build Pillow
        run: $(uv python find 3.14) -m pip wheel pillow -v

      - name: Find and move wheel file
        run: |
          # Find the wheel file with linux_x86_64 in the name
          WHEEL_FILE=$(find . -name "*linux_x86_64.whl" -type f | head -1)
          if [ -n "$WHEEL_FILE" ]; then
            echo "Found wheel file: $WHEEL_FILE"
            echo "WHEEL_FILENAME=$(basename $WHEEL_FILE)" >> $GITHUB_ENV
          else
            echo "No wheel file with linux_x86_64 found"
            exit 1
          fi

      - name: Add wheel file to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $WHEEL_FILENAME
          git commit -m "Add Pillow wheel: $WHEEL_FILENAME"
          git push